spring.application.name=nfc-tag-service
server.port=${PORT:8080}

#JPA & Hibernate ??
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.profiles.default=local

# Admin authentication
security.jwt.expiration=PT8H

# Resend Mail Configuration
resend.api-key=${RESEND_API_KEY:}
resend.from-email=${RESEND_FROM_EMAIL:noreply@mail.retapnfc.com}
