app.server-domain=${APP_SERVER_DOMAIN}
security.jwt.secret=${JWT_SECRET}
security.cookie.secure=true

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.properties.hibernate.default_schema=nfc

supabase.url=${SUPABASE_URL:}
supabase.service-key=${SUPABASE_SERVICE_KEY:}
supabase.bucket-name=${SUPABASE_BUCKET_NAME:tag-images}